version: '3'

volumes:
  pg_data: {}
  rabbitmq_data: {}
  traefik_acme: {}

services:

  backend: &backend
    restart: always
    build: ./backend
    expose:
      - "8000"
    links:
      - postgres:postgres
      - rabbitmq:rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:backend.dd.reckonsys.xyz"
    env_file: .env
    command: gunicorn -b :5000 wsgi:app

  worker:
    <<: *backend
    # command: /start-worker
    command: gunicorn -b :8000 wsgi:app

  traefik:
    image: traefik:v2.0.0-alpha4
    command: --api --docker
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - traefik_toml:/traefik.toml
      # - traefik_acme:/etc/traefik/acme/acme.json
    build: ./traefik
    depends_on:
      - backend
    ports:
      - "80"
      - "443"
        # - "0.0.0.0:443:443"

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  rabbitmq:
    restart: always
    image: rabbitmq:latest
    ports:
      - "5672"
    volumes:
      - rabbitmq_data:/data
