version: '3'

volumes:
  pg_data: {}
  traefik_acme: {}
  rabbitmq_data: {}

services:
  backend: &backend
    restart: always
    build: ./backend
    expose:
      - "8000"
    links:
      - postgres:postgres
      - rabbitmq:rabbitmq
    env_file: .env
    command: pipenv run gunicorn -b :5000 wsgi:app

  worker:
    <<: *backend
    # command: /start-worker
    command: pipenv run gunicorn -bind 0.0.0.0:8000 wsgi

  traefik:
    build: ./traefik
    depends_on:
      - backend
    volumes:
      - traefik_acme:/etc/traefik/acme
    ports:
      - "80"
      - "443"
        # - "0.0.0.0:443:443"

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  rabbitmq:
    restart: always
    image: rabbitmq:latest
    ports:
      - "5672"
    volumes:
      - rabbitmq_data:/data
