logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[retry]

[docker]
exposedByDefault = true


[Global]
debug = true

[log]
level = "DEBUG"

[accessLog]
# format = "json"

[api]
entryPoint = "traefik"
dashboard = true

[ping]

# Entrypoints, http and https
[entryPoints]
  # http should be redirected to https
  [entryPoints.http]
  address = ":80"
    # [entryPoints.http.redirect]
    # entryPoint = "https"
  # https is the default
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]


[file]
[backends]
  [backends.backend]
    [backends.backend.servers.server1]
      url = "http://backend:5000"

[frontends]
  [frontends.frontend]
  backend = "backend"
    [frontends.frontend.routes.backend]
    rule = "Host:backend.dd.reckonsys.xyz"



# Enable ACME (Let's Encrypt): automatic SSL
# [acme]
# Email address used for registration
# email = "dhilip@reckonsys.com"
# storage = "/etc/traefik/acme/acme.json"
# entryPoint = "https"
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
# onDemand = false
# OnHostRule = true
#   # Use a HTTP-01 acme challenge rather than TLS-SNI-01 challenge
#   [acme.dnsChallenge]
#     provider = "digitalocean"
#     delayBeforeCheck = 0
